name = "applicationplinko-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=applicationplinko.fr"
HMAC_KEY = "b886e827dabe58a19c20e17f0f4f985587e840043bef149bea69f2c5a8f5101a"
COOKIE_NAME = "ki0"
PLAY_PATH = "try"
BUTTON_ID = "p69186646992efb910b51602db7075890"
GATE_SALT = "97a70829f86509f1"
